name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Detect Package Manager
        id: detect-package-manager
        run: |
          if [ -f "yarn.lock" ]; then
            echo "::set-output name=runner::yarn";
          elif [ -f "package-lock.json" ]; then
            echo "::set-output name=runner::npm";
          fi

      - name: Build
        run: ${{ steps.detect-package-manager.outputs.runner }} next build --webpack

      - name: Deploy
        run: echo "Deploying to GitHub Pages..."